---
# file: roles/common/handlers/nfs.yml
- name: start NFS units
  service: name={{item}} state=restarted
  ignore_errors: yes 
  with_items:
   - netshare-networld.automount
   - netshare-users.automount
   - bindfs-depts.service

- name: stop NFS units
  service: name={{item}} state=stopped
  with_items:
   - netshare-networld.automount
   - netshare-users.automount
   - bindfs-depts.service
