---
# file: roles/workstations/tasks/main.yml
- include: ../../common/tasks/main.yml

- include: ../../common/tasks/rpmfusion.yml
- include: packages.yml
- include: libreoffice-arabic.yml
- include: clear-recent-users.yml
