---
# file: roles/workstations/tasks/packages.yml
- name: install school repository
  copy: src=school.repo dest=/etc/yum.repos.d
  tags:
   - install
   - packages
   - repos

- name: clear cache cookies
  command: find /var/cache/yum -iname cachecookie -delete
  tags:
   - install
   - packages
   - repos

- name: install GNOME Desktop for < F21
  yum: name="@^gnome-desktop-environment"
  when: ansible_distribution == "Fedora" and ansible_distribution_major_version|int < 21
  tags:
   - install
   - packages

- name: install GNOME Desktop for >= F21
  yum: name="@^workstation-product-environment"
  when: ansible_distribution == "Fedora" and ansible_distribution_major_version|int >= 21
  tags:
   - install
   - packages

- name: install langpack support
  yum: name="yum-langpacks"
  tags:
   - install
   - packages
   - languages

- name: install Arabic support
  command: yum -y langinstall "ar_LB"
  tags:
   - install
   - packages
   - languages

- name: install Armenian support
  command: yum -y langinstall "hy"
  tags:
   - install
   - packages
   - languages

- name: install French support
  command: yum -y langinstall "fr_FR"
  tags:
   - install
   - packages
   - languages

- name: install LibreOffice
  yum: name="@libreoffice"
  tags:
   - install
   - packages
   - libreoffice

- name: prepare to install Fonts
  command: yum -y group mark remove fonts
  tags:
   - install
   - packages
   - fonts

- name: install Fonts
  command: yum -y --exclude=larabie-uncommon-fonts --setopt="group_package_types=optional,default,mandatory" group install Fonts
  tags:
   - install
   - packages
   - fonts

- name: cleanup after installing Fonts
  command: yum -y group mark install fonts
  tags:
   - install
   - packages
   - fonts

- name: copy BZFlag pseudo-src rpm to /tmp
  copy: src=bzflag.src.rpm dest=/tmp/ mode=0644
  tags:
   - install
   - bzflag

- name: install dependencies for BZFlag compilation
  command: yum-builddep -y /tmp/bzflag.src.rpm
  tags:
   - install
   - bzflag
