---
# file: roles/workstations-school/tasks/ipa.yml

- name: install FreeIPA client on Fedora
  dnf: name={{ item }} state=present
  with_items:
   - freeipa-client
   - freeipa-admintools
  when: ansible_distribution == "Fedora"
  tags:
   - setup
   - accounts
   - ipa

- name: install FreeIPA client on CentOS
  dnf: name={{ item }} state=present
  with_items:
   - ipa-client
   - ipa-admintools
  when: ansible_distribution == "CentOS"
  tags:
   - setup
   - accounts
   - ipa

- include: ipa-{{ branch }}.yml
