---
# file: roles/workstations-school-net/tasks/abrt.yml

- name: Remove ABRT gui
  dnf: name={{item}} state=absent
  with_items:
   - abrt-desktop
   - abrt-gui
   - gnome-abrt
  tags:
   - install
   - abrt
