---
# file: roles/workstations-school/tasks/display-maanger.yml

- name: install LightDM
  yum: name={{item}} state=present
  with_items:
   - lightdm
   - lightdm-qt
   - lightdm-kde
  tags:
   - install
   - display-manager

- name: remove lightdm-gtk
  yum: name=lightdm-gtk state=absent
  tags:
   - install
   - display-manager

- name: set LightDM as display manager
  file: path=/etc/systemd/system/display-manager.service src=/usr/lib/systemd/system/lightdm.service state=link
  tags:
   - install
   - display-manager

- name: set graphic boot as default boot target
  file: path=/etc/systemd/system/default.target src=/lib/systemd/system/graphical.target state=link
  tags:
   - install
   - display-manager

- name: copy school theme files for LightDM for < F23
  copy: src=display-manager/lightdm-kde-1/lesbg dest=/usr/share/kde4/apps/lightdm-kde-greeter/themes/
  when: ansible_distribution != "Fedora" or ansible_distribution_major_version|int < 23
  tags:
   - install
   - display-manager

- name: copy school theme files for LightDM for >= F23
  copy: src=display-manager/lightdm-kde-2/lesbg dest=/usr/share/kde4/apps/lightdm-kde-greeter/themes/
  when: ansible_distribution == "Fedora" and ansible_distribution_major_version|int >= 23
  tags:
   - install
   - display-manager

- name: copy school config files for LightDM on < F23
  copy: src=display-manager/conf/1/ dest=/etc/lightdm/
  when: ansible_distribution == "Fedora" and ansible_distribution_major_version|int < 23
  tags:
   - install
   - display-manager

- name: copy school config files for LightDM on >= F23
  copy: src=display-manager/conf/2/ dest=/etc/lightdm/
  when: ansible_distribution != "Fedora" or ansible_distribution_major_version|int >= 23
  tags:
   - install
   - display-manager

- name: copy school scripts for LightDM for < F21
  copy: src=display-manager/scripts/ dest=/etc/lightdm/ mode=0755
  tags:
   - install
   - display-manager
  when: ansible_distribution == "Fedora" and ansible_distribution_major_version|int < 21

- name: copy school scripts for LightDM for >= F21
  copy: src=display-manager/scripts-newxloc/ dest=/etc/lightdm/ mode=0755
  tags:
   - install
   - display-manager
  when: ansible_distribution == "Fedora" and ansible_distribution_major_version|int >= 21

- name: copy screensaver config
  copy: src=display-manager/xscreensaver dest=/var/lib/lightdm
  tags:
   - install
   - display-manager

- name: set default session to GNOME
  file: src=gnome.desktop path=/usr/share/xsessions/default.desktop state=link
  tags:
   - install
   - display-manager

- name: install xscreensaver
  yum: name={{item}} state=present
  with_items:
   - xscreensaver-gl-extras
   - xscreensaver-gl-base
  tags:
   - install
   - display-manager

- name: install x11vnc
  yum: name=x11vnc state=present
  tags:
   - install
   - display-manager
