---
# file: roles/workstations/tasks/packages.yml

- name: install GNOME Desktop
  yum: name="@gnome-desktop-environment"
  tags:
   - install
#  command: yum -y groupinstall "GNOME Desktop"

- name: install Arabic support
  command: yum -y langinstall "ar_LB"
  tags:
   - install

- name: install Armenian support
  command: yum -y langinstall "hy"
  tags:
   - install

- name: install French support
  command: yum -y langinstall "fr_FR"
  tags:
   - install

- name: install LibreOffice
  yum: name="@libreoffice"
  tags:
   - install

- name: prepare to install Fonts
  command: yum -y group mark remove fonts
  tags:
   - install

- name: install Fonts
  command: yum -y --exclude=larabie-uncommon-fonts --setopt="group_package_types=optional,default,mandatory" group install Fonts
  tags:
   - install

- name: cleanup after installing Fonts
  command: yum -y group mark install fonts
  tags:
   - install

#- name: copy BZFlag pseudo-src rpm to /tmp
#  copy: src=bzflag.src.rpm dest=/tmp/ mode=0644
#  tags:
#   - install


