---
# file: roles/workstations-school/tasks/virt.yml
- name: Make os_images directory
  file: dest=/usr/share/os_images state=directory mode=0755
  tags:
   - install
   - virt

- name: Install VirtualBox files
  copy: src=virtualbox/.VirtualBox dest=/usr/share/os_images/
  tags:
   - install
   - virt

- name: Create snapshot symlink
  file: src=/var/tmp dest=/usr/share/os_images/.VirtualBox/Machines/Snapshots state=link
  tags:
   - install
   - virt

- name: Install VirtualBox hard drive
  command: rsync -avHPx /networld/system_data/virt/virt.vdi /usr/share/os_images/
  tags:
   - install
   - virt

- name: Install VirtualBox hard drive snapshot
  command: rsync -avHPx /networld/system_data/virt/{33bf5982-3a66-4da8-8526-771bdda82f37}.vdi /usr/share/os_images/.VirtualBox/Machines/Snapshots.orig/
  tags:
   - install
   - virt

- name: Install virt startup script
  copy: src=virtualbox/startvirt dest=/usr/bin mode=0755
  tags:
   - install
   - virt

- name: Install virt desktop file
  copy: src=virtualbox/startvirt.desktop dest=/usr/share/applications mode=0644
  tags:
   - install
   - virt
