---
# file: roles/workstations-school/tasks/main.yml
- include: ../../workstations-common/tasks/main.yml

- include: ../../common/tasks/disable-firewalld.yml

- include: ssh.yml
- include: logos.yml
- include: multiseat.yml
- include: display-manager.yml
- include: dconf.yml
- include: polkit.yml
- include: selinux.yml
- include: student-skel.yml
