---
# file: roles/workstations-school/tasks/selinux.yml

# Selinux must be disabled until the following are fixed:
# - xscreensaver can't access nfs folder under lightdm user, but denials aren't logged

- name: install required modules
  dnf: name={{item}} state=present
  with_items:
   - libsemanage-python
   - libselinux-python
  tags:
   - install
   - selinux

- name: set selinux to permissive
  selinux: policy=targeted state=permissive
  tags:
   - install
   - selinux

- name: set selinux nfs home dirs boolean
  seboolean: name=use_nfs_home_dirs state=yes persistent=yes
  ignore_errors: yes
  tags:
   - setup
   - selinux
