---
# file: roles/workstations-school/tasks/ssh.yml

- name: install ssh server
  dnf: name=openssh-server
  tags:
   - install
   - ssh

- name: be sure sshd service is enabled
  systemd: name=sshd enabled=yes
  tags:
   - install
   - atomic
   - ssh

- name: be sure sshd service is running
  systemd: name=sshd state=started
  ignore_errors: yes 
  tags:
   - install
   - atomic
   - ssh

- name: install public ssh host keys for school workstations
  copy: src=ssh-keys/{{item}} dest=/etc/ssh/ mode=0644
  notify:
   - restart ssh server
  with_items:
   - ssh_host_rsa_key.pub
   - ssh_host_ecdsa_key.pub
  tags:
   - install
   - atomic
   - ssh

- name: install private ssh host keys for school workstations
  copy: src=ssh-keys/{{item}} dest=/etc/ssh/ mode=0640 group=ssh_keys
  notify:
   - restart ssh server
  with_items:
   - ssh_host_rsa_key
   - ssh_host_ecdsa_key
  tags:
   - install
   - atomic
   - ssh

- name: create root user .ssh directory
  file: dest=/root/.ssh state=directory mode=0600
  tags:
   - install
   - atomic
   - ssh

- name: install public ssh root user files for school workstations
  copy: src=ssh-keys/{{item}} dest=/root/.ssh/ mode=0644
  with_items:
   - id_ecdsa.pub
   - known_hosts
  tags:
   - install
   - atomic
   - ssh

- name: install public ssh root user authorized keys for school workstations
  lineinfile: dest=/root/.ssh/authorized_keys state=present line="{{ lookup('file', 'ssh-keys/authorized_keys') }}"
  tags:
   - install
   - atomic
   - ssh

- name: install private ssh root user key for school workstations
  copy: src=ssh-keys/{{item}} dest=/root/.ssh/ mode=0640 group=ssh_keys
  with_items:
   - id_ecdsa
  tags:
   - install
   - atomic
   - ssh

