---
# file: roles/common/tasks/disable-firewalld.yml

- name: be sure firewalld is installed
  action: yum pkg=firewalld state=installed 
  tags:
   - install
   - firewalld
 
- name: be sure firewalld is disabled
  service: name=firewalld enabled=no
  tags:
   - install
   - firewalld

- name: be sure firewalld is stopped
  service: name=firewalld state=stopped
  ignore_errors: yes
  tags:
   - install
   - firewalld

