---
# file: roles/workstations-school/tasks/ipa.yml

- name: install FreeIPA client on Fedora
  yum: name={{item}} state=present
  with_items:
   - freeipa-client
   - freeipa-admintools
  when: ansible_distribution == "Fedora"
  tags:
   - setup
   - accounts
   - ipa

- name: install FreeIPA client on CentOS
  yum: name={{item}} state=present
  with_items:
   - ipa-client
   - ipa-admintools
  when: ansible_distribution == "CentOS"
  tags:
   - setup
   - accounts
   - ipa

- name: install lizardfs-client
  yum: name=lizardfs-client state=installed
  tags:
   - setup
   - accounts
   - ipa

- name: install LizardFS IPA config file
  copy: src=mfsmount-netshare.cfg dest=/var/tmp/ mode=0600
  tags:
   - setup
   - accounts
   - ipa

- name: create LizardFS IPA mount point
  file: path=/tmp/autojoin
        state=directory
        mode=0755
  tags:
   - setup
   - accounts
   - ipa

- name: mount location to access script
  command: mfsmount -c /var/tmp/mfsmount-netshare.cfg /tmp/autojoin
  tags:
   - setup
   - accounts
   - ipa

- name: join LESB&G FreeIPA domain
  command: /tmp/autojoin/networld/hd_images/linux/f23/autojoin.sh
  tags:
   - setup
   - accounts
   - ipa

- name: umount script location
  command: umount /tmp/autojoin
  tags:
   - setup
   - accounts
   - ipa

- name: remove LizardFS IPA config file
  file: name=/var/tmp/mfsmount-netshare.cfg state=absent
  tags:
   - setup
   - accounts
   - ipa
