---
# file: roles/workstations-school/tasks/ipa.yml

- name: install FreeIPA client
  yum: name={{item}} state=present
  with_items:
   - freeipa-client
   - freeipa-admintools
  tags:
   - setup
   - accounts

- name: mount location to access script
  mount: name=/mnt src=datastore02:/netshare/networld fstype=nfs opts=nolock state=mounted
  tags:
   - setup
   - accounts

- name: join LESB&G FreeIPA domain
  command: /mnt/hd_images/linux/f19/autojoin.sh
  tags:
   - setup
   - accounts

- name: umount script location
  mount: name=/mnt src=datastore02:/netshare/networld fstype=nfs state=unmounted
  tags:
   - setup
   - accounts

- name: remove script location from fstab
  mount: name=/mnt src=datastore02:/netshare/networld fstype=nfs state=absent
  tags:
   - setup
   - accounts
