---
# file: roles/common/tasks/nfs.yml
- name: setup NFS directories
  file: path=/netshare/{{item}}
        state=directory
        mode=0755
  with_items:
   - networld
  notify:
   - start NFS units
  tags:
   - install
   - nfs

- name: create symlink to users
  file: path=/netshare/users state=link src=/netshare/networld/usershare/users force=yes
  tags:
   - install
   - nfs

- name: create symlink to system_data
  file: path=/netshare/system_data state=link src=/netshare/networld/system_data force=yes
  tags:
   - install
   - nfs

- name: check whether system home dir is a symlink
  stat: path=/home follow=no
  register: home_path
  tags:
   - install
   - nfs

- name: backup system home dir
  shell: removes=/home mv /home /home-`date -Iseconds`.bak
  when: home_path.stat.islnk is defined and home_path.stat.islnk == False
  tags:
   - install
   - nfs

- name: create symlink from /home to /netshare/users
  file: path=/home state=link src=/netshare/users force=yes
  when: home_path.stat.islnk is not defined or home_path.stat.islnk == False
  tags:
   - install
   - nfs

- name: check whether networld is a symlink
  stat: path=/networld follow=no
  register: home_path
  tags:
   - install
   - nfs

- name: backup networld dir
  shell: removes=/networld mv /networld /networld-`date -Iseconds`.bak
  when: home_path.stat.islnk is defined and home_path.stat.islnk == False
  tags:
   - install
   - nfs

- name: create symlink from /networld to /netshare/networld
  file: path=/networld state=link src=/netshare/networld
  when: home_path.stat.islnk is not defined or home_path.stat.islnk == False
  tags:
   - install
   - nfs

- name: setup bindfs path
  file: path=/var/tmp/bindfs state=directory mode=0755
  tags:
   - install
   - nfs

- name: install bindfs, nfs-utils and rpcbind
  yum: name={{item}} state=installed
  with_items:
   - bindfs
   - rpcbind
   - nfs-utils
  tags:
   - install
   - nfs

- name: setup NFS units
  copy: src=lest/{{item}} dest=/etc/systemd/system/{{item}} mode=0644
  with_items:
   - netshare-networld.automount
   - netshare-networld.mount
   - bindfs-world.service
  notify:
   - start NFS units
  tags:
   - install
   - nfs

- name: enable NFS units
  service: name={{item}} enabled=yes
  with_items:
   - netshare-networld.automount
   - bindfs-world.service
  tags:
   - install
   - nfs

- meta: flush_handlers
