---
# file: roles/common/tasks/nfs.yml
- name: setup NFS directories
  file: path=/netshare/{{item}}
        state=directory
        mode=0755
  with_items:
   - networld
   - users
  notify:
   - start NFS units
  tags:
   - install
   - nfs

- name: check whether system home dir is a symlink
  stat: path=/home follow=no
  register: home_path
  tags:
   - install
   - nfs

- name: backup system home dir
  shell: removes=/home mv /home /home-`date -Iseconds`.bak
  when: home_path.stat.islnk is defined and home_path.stat.islnk == False
  tags:
   - install
   - nfs

- name: create symlink from /home to /netshare/users
  file: path=/home state=link src=/netshare/users
  when: home_path.stat.islnk is not defined or home_path.stat.islnk == False
  tags:
   - install
   - nfs

- name: check whether networld is a symlink
  stat: path=/networld follow=no
  register: home_path
  tags:
   - install
   - nfs

- name: backup networld dir
  shell: removes=/networld mv /networld /networld-`date -Iseconds`.bak
  when: home_path.stat.islnk is defined and home_path.stat.islnk == False
  tags:
   - install
   - nfs

- name: create symlink from /networld to /netshare/networld
  file: path=/networld state=link src=/netshare/networld
  when: home_path.stat.islnk is not defined or home_path.stat.islnk == False
  tags:
   - install
   - nfs

- name: install bindfs, nfs-utils and rpcbind
  yum: name={{item}} state=installed
  with_items:
   - bindfs
   - rpcbind
   - nfs-utils
  tags:
   - install
   - nfs

- name: setup NFS units
  copy: src={{item}} dest=/usr/lib/systemd/system/{{item}} mode=0644
  with_items:
   - netshare-networld.automount
   - netshare-networld.mount
   - netshare-users.automount
   - netshare-users.mount
   - bindfs-depts.service
  notify:
   - start NFS units
  tags:
   - install
   - nfs

- name: enable NFS units
  service: name={{item}} enabled=yes
  with_items:
   - netshare-networld.automount
   - netshare-users.automount
   - bindfs-depts.service
  tags:
   - install
   - nfs

- meta: flush_handlers
