---
# file: roles/common/tasks/main.yml

- name: be sure ntp and ntpdate are installed
  action: yum pkg=ntp state=installed 
  tags: ntp
 
#- name: be sure ntp is configured
#  template: src=ntp.conf.j2 dest=/etc/ntp.conf
#  notify:
#    - restart ntpd
#  tags: ntp

- name: be sure ntpd is running and enabled
  service: name=ntpd state=running enabled=yes
  tags: ntp

- name: be sure ntpdate is enabled
  service: name=ntpdate enabled=yes
  tags: ntp
