---
# file: roles/common/tasks/rpmfusion.yml

- name: check whether rpmfusion repos are installed
  file: path=/etc/yum.repos.d/{{item}}.repo state=file
  register: rpmfusion_result
  ignore_errors: True
  with_items:
   - rpmfusion-free
   - rpmfusion-nonfree 
  tags:
   - install
   - rpmfusion
   - repo

- name: add skeleton rpmfusion repos to /etc/yum.repos.d
  copy: src={{item}}.repo dest=/etc/yum.repos.d/{{item}}-temp.repo mode=0644
  with_items:
   - rpmfusion-free
   - rpmfusion-nonfree
   - rpmfusion-free-updates
   - rpmfusion-nonfree-updates
  when: rpmfusion_result|failed
  tags:
   - install
   - rpmfusion
   - repo

- name: install rpmfusion-free-release
  dnf: name=rpmfusion-free-release
       disable_gpg_check=yes
       state=present
  when: rpmfusion_result|failed
  tags:
   - install
   - rpmfusion
   - repo

- name: install rpmfusion-nonfree-release
  dnf: name=rpmfusion-nonfree-release
       disable_gpg_check=yes
       state=present
  when: rpmfusion_result|failed
  tags:
   - install
   - rpmfusion
   - repo

- name: remove skeleton rpmfusion repos from /etc/yum.repos.d
  file: path=/etc/yum.repos.d/{{item}}-temp.repo
        state=absent
  with_items:
   - rpmfusion-free
   - rpmfusion-nonfree
   - rpmfusion-free-updates
   - rpmfusion-nonfree-updates
  when: rpmfusion_result|failed
  tags:
   - install
   - rpmfusion
   - repo

# We use a local mirror that intercepts http requests, but not https requests, so disable https 
- name: turn off https links in rpmfusion yum repo
  lineinfile: dest=/etc/yum.repos.d/rpmfusion-{{item}}.repo
              backrefs=yes
              regexp="metalink(.*)https(.*)metalink(.*)(fedora-\$release)(.*)"
              line="mirrorlist\1http\2mirrorlist\3\4\5"
              state=present
  with_items:
   - free
   - nonfree
  notify:
   - clear yum cache
   - create empty yum cache
  when: ansible_distribution == "Fedora"
  tags:
   - install
   - atomic
   - yum
   - repo

- name: turn off https links in rpmfusion updates yum repo
  lineinfile: dest=/etc/yum.repos.d/rpmfusion-{{item}}-updates.repo
              backrefs=yes
              regexp="metalink(.*)https(.*)metalink(.*)(updates-released-\$release)(.*)"
              line="mirrorlist\1http\2mirrorlist\3\4\5"
              state=present
  with_items:
   - free
   - nonfree
  notify:
   - clear yum cache
   - create empty yum cache
  when: ansible_distribution == "Fedora"
  tags:
   - install
   - atomic
   - yum
   - repo
