---
# file: roles/workstations-school-standalone/tasks/display-manager.yml

- name: remove LightDM
  dnf: name={{item}} state=absent
  with_items:
   - lightdm
   - lightdm-qt
  tags:
   - install
   - display-manager

- name: remove lightdm-gtk
  dnf: name=lightdm-gtk state=absent
  tags:
   - install
   - display-manager

- name: set GDM as display manager
  file: path=/etc/systemd/system/display-manager.service src=/usr/lib/systemd/system/gdm.service state=link
  tags:
   - install
   - atomic
   - display-manager

- name: set graphic boot as default boot target
  file: path=/etc/systemd/system/default.target src=/lib/systemd/system/graphical.target state=link
  tags:
   - install
   - atomic
   - display-manager

- name: remove LightDM config
  file: path={{item}} state=absent
  with_items:
   - /var/lib/lightdm
   - /etc/lightdm
  tags:
   - install
   - atomic
   - display-manager

- name: set default session to GNOME
  file: src=gnome.desktop path=/usr/share/xsessions/default.desktop state=link
  tags:
   - install
   - atomic
   - display-manager

- name: remove xscreensaver
  dnf: name={{item}} state=absent
  with_items:
   - xscreensaver-gl-extras
   - xscreensaver-gl-base
  tags:
   - install
   - display-manager

- name: disable GNOME initial setup
  copy: src=display-manager/custom.conf dest=/etc/gdm
  tags:
   - install
   - atomic
   - display-manager


