---
# file: roles/workstations-school-standalone/tasks/wifi.yml

- name: autoconnect to {{ branch }} wifi hotspots
  copy: src=network-scripts/{{ branch }}/ifcfg/ dest=/etc/sysconfig/network-scripts mode=0644
  tags:
   - install
   - atomic
   - network
  ignore_errors: true

- name: copy wifi keys
  copy: src=network-scripts/{{ branch }}/keys/ dest=/etc/sysconfig/network-scripts mode=0600
  tags:
   - install
   - atomic
   - network
  ignore_errors: true
